### ISSUE TITLE
A few more edits needed in dev branch

### ISSUE THREAD

**Issue by blue-santa** [siddhartha-komodo/komodo-docs-vuepress#11]
So far so good, gcharang. 

I've found a workaround for making changes locally, so that helps a lot.

Here's one question:

number                                       |(numeric)                    |the transactions before this one (by 1-based index in "transactions" list) that must be present in the final block, if this one is

The description is a little unclear, and it also has parantheses in the middle of the thought.

Can you try rewriting this so that the meaning is more clear and any side information is given afterwards, and preferrably in a proper sentence instead of parens?
Here is another such case, also in the mining.md file. Can you please work on the phrasing and remove the need for parentheses?

|the priority to add or subtract (the transaction selection algorithm assigns the tx a higher priority; (transaction priority calculation: `coinage * value_in_satoshis / txsize`))
Another case:

only the algorithm for selecting transactions into a block considers the transaction as it paid a higher (or lower) fee.
siddhartha-komodoToday at 2:16 PM
The gettransaction method in the wallet.md file has a few arrays that need a bit more description in the type column. Can you please take a look at that?
siddhartha-komodoToday at 2:24 PM
Another thing to address.

In this sentence here:

They all form a cluster with the same N value where the base tokens in all the chains in that cluster are fungible via the burn protocol.

Who is "they"? Is it the notary nodes? The pubkeys? The asset chains? Need to be specific.

I rewrote to this:

All asset chains that has the same `ac_cc` value form a cluster, where the base tokens of all the chains in the cluster are fungible via the burn protocol.
I'm putting all of these notes in an issue so they're easier to track.

**Comment by gcharang** [comment]
I have added a commit dealing with the above things in the PR#14
