### ISSUE TITLE
Four missing or potentially inaccurate properties in gatewaysinfo

### ISSUE THREAD

**Issue by siddhartha-komodo** [siddhartha-komodo/komodo-docs-vuepress#6]
taddr, prefix, prefix2, and deposit are all potentially inaccurate.

https://siddhartha-komodo.github.io/komodo-docs-vuepress/basic-docs/cryptoconditions/cc-gateways.html#gatewaysinfo

**Comment by gcharang** [comment]
jl's comment: taddr, prefix, prefix2 are the coin specific address prefixes that are customizing the address for bitcoin vs. KMD vs LTC,e tc

**Comment by siddhartha-komodo** [comment]
Thanks. Fixed.
