### ISSUE TITLE
<aside class="notice">

### ISSUE THREAD

**Issue by gcharang** [siddhartha-komodo/komodo-docs-vuepress#9]
In https://github.com/siddhartha-komodo/komodo-docs-vuepress/blob/master/docs/basic-docs/installations/basic-instructions.md there is a `<aside class="notice">` being called, but I think class="notice" is not defined.

**Comment by siddhartha-komodo** [comment]
This was from Slate. I must not have updated the format to `::: tip`, as we have elsewhere.

I've fixed this now. Thank you.
